config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "projects/:project_id/time_logs/:id", to: "time_logs#show", as: "project_time_log_path"
  get "projects/:project_id/payments/:id", to: "payments#show", as: "project_payment_path"

  namespace :admin do
    get "projects/index"
    get "projects/show"
  end
  namespace :api do
    namespace :v1 do
      resources :users, param: :_username
      post "/auth/login", to: "authentication#login"
      # get "/*a", to: "application#not_found"
      resource :user, controller: "profile" do
        collection do
          get "change_password"
          patch "update_password"
        end
      end
      resources :comments
      resources :projects do
        resources :payments
        resources :time_logs
      end
      resources :users
      resources :clients
    end
  end
  namespace :admin do
    match ":id" => "users#destroy", :via => :delete, :as => :user_delete
    resources :users
    resources :clients
    resources :projects do
      resources :payments
      resources :time_logs
    end
  end

  namespace :manager do
    resources :users, only: %i[index]
    resources :clients
    resources :projects do
      resources :payments
      resources :time_logs
    end
  end
  namespace :employee do
    resources :clients, only: %i[index show]
    resources :projects, only: %i[index show] do
      resources :time_logs
    end
  end
  resources :comments

  resource :user, controller: "users" do
    collection do
      get "change_password"
      patch "update_password"
    end
  end
  # get "/*a", to: "application#not_found"
  devise_for :users, controllers: { registrations: "users/registrations" }

  get "register", to: "users#new"
  post "register", to: "users#add_user"

  namespace :dashboard do
    get "dashboard/index"
  end

  get "dashboard/index"
  root to: "pages#index"

  namespace :dashboard do
    root to: "dashboard#index"
  end

  get "*path", controller: "application", action: "page_not_found"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
# frozen_string_literal: true

class Client < ApplicationRecord
  paginates_per 7
  has_many :projects, dependent: :delete_all

  validates :email, uniqueness: true
  validates :name, presence: true

  def self.apply_filter(params)
    @clients = Client.all # creates an anonymous scope
    @clients = @clients.where("name like ?", "#{params[:name]}%") if params[:name].present?
    @clients = @clients.where(params[:email]) if params[:email].present?
    @clients = @clients.where("company like ?", "#{params[:company]}%") if params[:company].present?
    @clients
  end
end

app/controllers/admin/clients_controller.rb
# frozen_string_literal: true

class Admin::ClientsController < ApplicationController
  before_action :set_client, only: %i[edit update destroy show]

  def new
    authorize(Client)
  end

  def show
    authorize(@client)
  end

  def index
    authorize(Client)
    @clients = Client.apply_filter(params)
    @clients = @clients.page(params[:page])
  end

  def edit; end

  def update
    authorize @client

    if @client.update(create_params)
      redirect_to admin_client_path(@client), notice: 'Client was successfully updated. '
    else
      render :edit
    end
  end

  def destroy
    authorize(@client)
    @client.destroy
    redirect_to admin_clients_path, notice: 'Client deleted.'
  end

  def create
    authorize(Client)
    @client = Client.new(create_params)
    if @client.save
      redirect_to admin_client_path(@client), notice: 'Client was successfully created. '
    else
      render :new
    end
  end

  def create_params
    params.require(:client).permit(:name, :email, :company, :phone, :referred_by, :country, :compnay_phone)
  end

  def set_client
    @client = Client.find_by_id(params[:id])
    redirect_to(root_url, notice: 'Client not found') unless @client
  end

  def authorize(record, query = nil)
    super([:admin, record], query)
  end
end

app/controllers/api/v1/admin/clients_controller.rb
# frozen_string_literal: true

class Api::V1::Admin::ClientsController < Api::V1::BaseController
  before_action :set_client, only: %i[edit update destroy show]

  def index
    # authorize (Client)
    @clients = Client.all
    render json: @clients
  end

  def create
    # authorize(Client)
    @client = Client.new(create_params)
    if @client.save
      render json: @client
    else
      render json: { error: 'Error Creating client.' }
    end
  end

  def show
    render json: @client
  end

  def update
    if @client.update(create_params)
      render json: @client
    else
      render json: { error: 'Error updating client.' }
    end
  end

  def destroy
    # authorize(@client)
    @client.destroy
    render json: { message: 'Client deleted successfully.' }
  end

  def create_params
    params.permit(:name, :email, :company, :phone, :referred_by, :country, :compnay_phone)
  end

  def set_client
    @client = Client.find_by_id(params[:id])
  end

  def authorize(record, query = nil)
    super([:api, :v1, :admin, record], query)
  end
end

app/controllers/api/v1/clients_controller.rb
# frozen_string_literal: true

class Api::V1::ClientsController < Api::V1::BaseController
  before_action :set_client, only: %i[edit update destroy show]

  def index
    @clients = Client.apply_filter(params)
    @clients = @clients.page(params[:page])
    render json: @clients
  end

  def create
    @client = Client.new(create_params)
    if @client.save
      render_success("Successfully created the client", @client)
    else
      render_errors(@client)
    end
  end

  def show
    render json: @client
  end

  def update
    if @client.update(create_params)
      render_success("Successfully updated the client", @client)
    else
      render_errors(@client)
    end
  end

  def destroy
    # authorize(@client)
    @client.destroy
    render_success("Successfully deleted the client")
  end

  def create_params
    params.permit(:name, :email, :company, :phone, :referred_by, :country, :compnay_phone)
  end

  def set_client
    @client = Client.find(params[:id])
  end

  def authorize(record, query = nil)
    super([:api, :v1, record], query)
  end
end

app/controllers/employee/clients_controller.rb
# frozen_string_literal: true

class Employee::ClientsController < ApplicationController
  before_action :set_client, only: %i[show]

  def show; end

  def index
    @clients = Client.apply_filter(params)
    @clients = @clients.page(params[:page])
  end

  def set_client
    @client = Client.find_by_id(params[:id])
    redirect_to(root_url, notice: 'Client not found') unless @client
  end
end

app/controllers/manager/clients_controller.rb
# frozen_string_literal: true

class Manager::ClientsController < ApplicationController
  before_action :set_client, only: %i[edit update destroy show]

  def new
    authorize(Client)
  end

  def show
    authorize(@client)
  end

  def index
    authorize(Client)
    @clients = Client.apply_filter(params)
    @clients = @clients.page(params[:page])
  end

  def edit
    authorize(@client)
  end

  def update
    authorize(@client)

    if @client.update(create_params)
      redirect_to manager_client_path(@client), notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  def create
    authorize(Client)
    @client = Client.new(create_params)
    if @client.save
      redirect_to manager_client_path(@client), notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  def create_params
    params.require(:client).permit(:name, :email, :company, :phone, :referred_by, :country, :compnay_phone)
  end

  def set_client
    @client = Client.find_by_id(params[:id])
    redirect_to(dashboard_root_path, notice: 'Record not found') unless @client
  end

  def authorize(record, query = nil)
    super([:manager, record], query)
  end
end

app/helpers/admin/clients_helper.rb
# frozen_string_literal: true

module Admin::ClientsHelper
  def options_for_countries
    [%w[Pakistan],
     %w[America]]
    end
end

app/helpers/api/v1/admin/clients_helper.rb
# frozen_string_literal: true

module Api::V1::Admin::ClientsHelper
end

app/helpers/api/v1/clients_helper.rb
# frozen_string_literal: true

module Api::V1::ClientsHelper
end

app/helpers/api/v1/employee/clients_helper.rb
# frozen_string_literal: true

module Api::V1::Employee::ClientsHelper
end

app/helpers/api/v1/manager/clients_helper.rb
# frozen_string_literal: true

module Api::V1::Manager::ClientsHelper
end

app/helpers/employee/clients_helper.rb
# frozen_string_literal: true

module Employee::ClientsHelper
end

app/helpers/manager/clients_helper.rb
# frozen_string_literal: true

module Manager::ClientsHelper
  def options_for_countries
    [%w[Pakistan],
     %w[America]]
  end
end

app/views/admin/clients/_edit-form.html.erb
<div class='row'>
  <%= link_to 'Back', url_for(:back), class:'btn btn-secondary pull-right' %>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-sm-9 col-md-7 col-lg-5 mx-auto'>
      <div class='card card-signin my-5'>
        <div class='card-body'>
          <h5 class='card-title text-center'>Edit client</h5>
          <%= form_for(@client, url:admin_client_path) do |f| %>
            <div class='form-group'>
              <label>Full Name:</label>
              <%= f.text_field :name, autofocus: true, autocomplete: 'Name',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Email:</label>
              <%= f.email_field :email, autofocus: true, autocomplete: 'email',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Company:</label>
              <%= f.text_field :company, autofocus: true, autocomplete: 'company',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Phone:</label>
              <%= f.text_field :phone, autofocus: true, autocomplete: 'Phone',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Company Phone:</label>
              <%= f.text_field :compnay_phone, autofocus: true, autocomplete: 'Company',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Country:</label>
              <%= f.select :country, options_for_countries, {}, prompt: 'Select One', class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Referred by:</label>
              <%= f.text_field :referred_by, autofocus: true, autocomplete: 'Referred by(Company,person)',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <% if current_page?(controller: 'admin/clients', action: 'new') %>
              <%= f.submit('Create', class:'btn btn-primary  btn-block') %>
            <% else %>
              <%= f.submit('Update', class:'btn btn-primary  btn-block') %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/clients/_form.html.erb
<div class='row'>
  <%= link_to 'Back', url_for(:back), class:'btn btn-secondary pull-right' %>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-sm-9 col-md-7 col-lg-5 mx-auto'>
      <div class='card card-signin my-5'>
        <div class='card-body'>
          <h5 class='card-title text-center'>Create client</h5>
          <%= form_for Client.new, url: admin_clients_path do |f| %>
            <div class='form-group'>
              <label>Full Name:</label>
              <%= f.text_field :name, autofocus: true, autocomplete: 'name' ,class:'form-control' , required:true %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Email:</label>
              <%= f.email_field :email, autofocus: true, autocomplete: 'email',class:'form-control', required:true %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Company:</label>
              <%= f.text_field :company, autofocus: true, autocomplete: 'company',class:'form-control', required:true %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Phone:</label>
              <%= f.text_field :phone, autofocus: true, autocomplete: 'Phone',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Company Phone:</label>
              <%= f.text_field :compnay_phone, autofocus: true, autocomplete: 'Company',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Country:</label>
              <%= f.select :country, options_for_countries, {}, prompt: 'Select One', class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Referred by:</label>
              <%= f.text_field :referred_by, autofocus: true, autocomplete: 'Referred by(Company,person)',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <% if current_page?(controller: 'admin/clients', action: 'new') %>
              <%= f.submit('Create', class:'btn btn-primary  btn-block') %>
            <% else %>
              <%= f.submit('Update', class:'btn btn-primary  btn-block') %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/clients/index.html.erb
<p id='notice'><%= notice %></p>
<%= render 'clients/search', url: admin_clients_path %>
<div class='row'>
  <div class='well'>
    <div class='span7'>
      <div class='widget stacked widget-table action-table'>
        <div class='widget-header'>
          <i class='icon-th-list'></i>
          <%= link_to(new_admin_client_path, class:'btn btn-primary btn-xs pull-left' ) do %>
            <i class='fa fa-eye'> Create client </i>
          <% end %>
        </div>
        <!-- /widget-header -->
        <div class='widget-content'>
          <table class='table table-striped table-bordered'>
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Company</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @clients.each do |person| %>
                <tr>
                  <td><%= person.name %> </td>
                  <td><%= person.email %> </td>
                  <td><%= person.phone %> </td>
                  <td><%= person.company %> </td>
                  <td>
                    <span> <%= link_to(admin_client_path(person), class:'btn btn-info btn-xs glyphicon glyphicon-edit') do %>
                        <i class='fa fa-eye'></i>
                      <% end %>
                    </span>
                    <span>
                      <%= link_to(edit_admin_client_path(person), class:'btn btn-info btn-xs glyphicon glyphicon-edit') do %>
                        <i class='fa fa-edit'></i>
                      <% end %>
                    </span>
                    <span>
                      <%= link_to('Delete',admin_client_path(person), method: :delete, data: {confirm: 'are you sure?'} ,class:'btn btn-warning btn-xs glyphicon glyphicon-edit')%>
                    </span>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @clients %>
        </div>
        <!-- /widget-content -->
      </div>
      <!-- /widget -->
    </div>
  </div>
</div>

app/views/admin/clients/show.html.erb
<div class='row'>
  <%= link_to 'Back', url_for(:back), class:'btn btn-secondary pull-right' %>
</div>
<div class='container main-secction'>
  <div class='row'>
    <div class='col-md-12 col-sm-12 col-xs-12 image-section'>
      <%= image_tag 'https://png.pngtree.com/thumb_back/fw800/back_pic/00/08/57/41562ad4a92b16a.jpg' %>
    </div>
    <div class='row user-left-part'>
      <div class='col-md-3 col-sm-3 col-xs-12 user-profil-part pull-left'>
      </div>
      <div class='col-md-9 col-sm-9 col-xs-12 pull-right profile-right-section'>
        <div class='row profile-right-section-row'>
          <div class='col-md-12 profile-header'>
            <div class='row'>
              <div class='col-md-8 col-sm-6 col-xs-6 profile-header-section1 pull-left'>
                <h1><%= @client.name %></h1>
                <h5><%= @client.company %></h5>
              </div>
              <div class='col-md-4 col-sm-6 col-xs-6 profile-header-section1 text-right pull-rigth'>
                <%= link_to('Edit Client', edit_admin_client_path(@client), html_options = {class:'btn btn-primary btn-block'}) %>
                <%= link_to('Delete',admin_client_path(@client), method: :delete, data:{confirm: 'are you sure?'} ,class:'btn btn-danger  btn-block') %>
              </div>
            </div>
          </div>
          <div class='col-md-12'>
            <div class='row'>
              <div class='col-md-8'>
                <ul class='nav nav-tabs' role='tablist'>
                  <li class='nav-item'>
                    <a class='nav-link active' href='#profile' role='tab' data-toggle='tab'><i class='fas fa-user-circle'></i> Personal Infromation</a>
                  </li>
                  <li class='nav-item'>
                    <a class='nav-link' href='#buzz' role='tab' data-toggle='tab'><i class='fas fa-info-circle'></i> Other Information</a>
                  </li>
                  <li class='nav-item'>
                    <a class='nav-link' href='#projects' role='tab' data-toggle='tab'><i class='fas fa-info-circle'></i> Projects</a>
                  </li>
                </ul>
                <!-- Tab panes -->
                <div class='tab-content'>
                  <div role='tabpanel' class='tab-pane fade show active' id='profile'>
                    <div class='row'>
                      <div class='col-md-2'>
                        <label>ID</label>
                      </div>
                      <div class='col-md-6'>
                        <p><%= @client.id %></p>
                      </div>
                    </div>
                    <div class='row'>
                      <div class='col-md-2'>
                        <label>Name</label>
                      </div>
                      <div class='col-md-6'>
                        <p><%= @client.name %></p>
                      </div>
                    </div>
                    <div class='row'>
                      <div class='col-md-2'>
                        <label>Email</label>
                      </div>
                      <div class='col-md-6'>
                        <p><%= @client.email %></p>
                      </div>
                    </div>
                    <div class='row'>
                      <div class='col-md-2'>
                        <label>Telephone</label>
                      </div>
                      <div class='col-md-6'>
                        <p><%= @client.phone %></p>
                      </div>
                    </div>
                  </div>
                  <div role='tabpanel' class='tab-pane fade' id='buzz'>
                    <div class='row'>
                      <div class='col-md-6'>
                        <label>Company</label>
                      </div>
                      <div class='col-md-6'>
                        <p><%= @client.company %></p>
                      </div>
                    </div>
                    <div class='row'>
                      <div class='col-md-6'>
                        <label>Company Phone</label>
                      </div>
                      <div class='col-md-6'>
                        <p><%= @client.compnay_phone %></p>
                      </div>
                    </div>
                    <div class='row'>
                      <div class='col-md-6'>
                        <label>Total Projects</label>
                      </div>
                      <div class='col-md-6'>
                        <p><%= %>0</p>
                      </div>
                    </div>
                    <div class='row'>
                      <div class='col-md-6'>
                        <label>Country</label>
                      </div>
                      <div class='col-md-6'>
                        <p><%= @client.country %></p>
                      </div>
                    </div>
                    <div class='row'>
                      <div class='col-md-6'>
                        <label>Language</label>
                      </div>
                      <div class='col-md-6'>
                        <p><%= %>English</p>
                      </div>
                    </div>
                  </div>
                  <div role='tabpanel' class='tab-pane fade' id='projects'>
                    <% @client.projects.each do |project| %>
                      <div class='col-md-12'>
                        <label><%= link_to project.name, manager_project_path(project.id) %></label>
                      </div>
                    <%end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>