config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "projects/:project_id/time_logs/:id", to: "time_logs#show", as: "project_time_log_path"
  get "projects/:project_id/payments/:id", to: "payments#show", as: "project_payment_path"

  namespace :admin do
    get "projects/index"
    get "projects/show"
  end
  namespace :api do
    namespace :v1 do
      resources :users, param: :_username
      post "/auth/login", to: "authentication#login"
      # get "/*a", to: "application#not_found"
      resource :user, controller: "profile" do
        collection do
          get "change_password"
          patch "update_password"
        end
      end
      resources :comments
      resources :projects do
        resources :payments
        resources :time_logs
      end
      resources :users
      resources :clients
    end
  end
  namespace :admin do
    match ":id" => "users#destroy", :via => :delete, :as => :user_delete
    resources :users
    resources :clients
    resources :projects do
      resources :payments
      resources :time_logs
    end
  end

  namespace :manager do
    resources :users, only: %i[index]
    resources :clients
    resources :projects do
      resources :payments
      resources :time_logs
    end
  end
  namespace :employee do
    resources :clients, only: %i[index show]
    resources :projects, only: %i[index show] do
      resources :time_logs
    end
  end
  resources :comments

  resource :user, controller: "users" do
    collection do
      get "change_password"
      patch "update_password"
    end
  end
  # get "/*a", to: "application#not_found"
  devise_for :users, controllers: { registrations: "users/registrations" }

  get "register", to: "users#new"
  post "register", to: "users#add_user"

  namespace :dashboard do
    get "dashboard/index"
  end

  get "dashboard/index"
  root to: "pages#index"

  namespace :dashboard do
    root to: "dashboard#index"
  end

  get "*path", controller: "application", action: "page_not_found"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  mount_uploaders :files, FileUploader
  searchkick word_start: [:title, :description, :cost]
  paginates_per 7

  serialize :files, JSON # If you use SQLite, add this line.

  belongs_to :manager, class_name: "User"
  belongs_to :client

  has_and_belongs_to_many :employees, join_table: "employees_projects", optional: true

  has_many :payments, dependent: :delete_all
  has_many :time_logs, dependent: :delete_all
  has_many :comments, as: :commentable, dependent: :delete_all

  validates :manager, presence: true
  validates :client, presence: true

  def self.apply_filter(params, current_user)
    @projects = if current_user.employee?
                  current_user.projects
                else
                  Project.all # creates an anonymous scope
                end
    @projects = @projects.where("name like ?", "#{params[:title]}%") if params[:title].present?
    @projects
  end

  def add_employees(project_params)
    employee_ids = project_params[:employees]
    employee_ids.delete("")
    self.employees = Employee.find(employee_ids)
  end

  def search_data
    {
      title: title,
      description: description,
      cost: cost,
    }
  end
end

app/controllers/admin/projects_controller.rb
# frozen_string_literal: true

class Admin::ProjectsController < ProjectsController
  def create
    # authorize(Project)
    super
    if @project.save(project_params.except(:employees))
      redirect_to admin_project_path(@project), notice: 'Project was successfully created.'
    else
      render :new
   end
  end

  def update
    authorize(@project)
    super

    if @project.update(project_params.except(:employees))
      redirect_to admin_projects_index_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize(@project)
    super

    redirect_to admin_projects_index_path, notice: 'Project was successfully destroyed.'
  end

  def show
    super
    authorize(@project)
    respond_to do |format|
      format.html { render 'projects/show', project: @project, _url: admin_project_path }
      format.pdf do
        render pdf: 'Your_filename',
               template: 'projects/show.html.erb',
               layout: 'pdf.html'
      end
    end
  end

  def index
    authorize(Project)
    super
  end

  def authorize(record, query = nil)
    super([:admin, record], query)
  end
end

app/controllers/api/v1/projects_controller.rb
# frozen_string_literal: true

class Api::V1::ProjectsController < Api::V1::BaseController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_user, only: %i[show index]
  before_action :validate_user, only: %i[update create]

  def index
    @projects = Project.apply_filter(params, @current_user)
    render json: @projects
  end

  def create
    @project = Project.new(project_params.except(:employees))
    @project.creator_id = current_user.id
    @project.add_employees(project_params)

    if @project.save(project_params.except(:employees))
      render_success("Successfully updated the project", @project)
    else
      render_errors(@project)
    end
  end

  def update
    @project.add_employees(project_params)
    if @project.update(project_params.except(:employees))
      render_success("Successfully updated the project", @project)
    else
      render_errors(@project)
    end
  end

  def show
    render json: @project
  end

  def destroy
    @project.destroy
    render json: { message: "Deleted project." }
  end

  def set_project
    @project = Project.find(params[:id])
    render not_found unless @project
  end

  def set_user
    @user = User.find(@current_user.id)
  end

  def project_params
    params.require(:project).permit(:name, :description, :manager_id, :client_id, :creator_id, :cost, employees: [], files: [])
  end

  def validate_user
    render json: { erro: "You are not authorized to perform this action" } if @current_user.employee?
  end

  def authorize(record, query = nil)
    super([:api, :v1, record], query)
  end
end

app/controllers/employee/projects_controller.rb
# frozen_string_literal: true

class Employee::ProjectsController < ProjectsController
  def show
    super
    render 'projects/show', project: @project, _url: employee_project_path
  end
end

app/controllers/manager/projects_controller.rb
# frozen_string_literal: true

class Manager::ProjectsController < ProjectsController
  def create
    authorize(Project)
    super
    if @project.save
      redirect_to manager_projects_path, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    super
    authorize(@project)

    if @project.update(project_params.except(:employees))
      redirect_to manager_projects_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def index
    authorize(Project)
    super
  end

  def show
    authorize(Project)
    super
    render 'projects/show', project: @project, _url: manager_project_path
  end

  def destroy
    authorize(Project)
  end

  def authorize(record, query = nil)
    super([:manager, record], query)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_user, only: %i[show index]

  def index
    @projects = Project.apply_filter(params, @current_user)
    @projects = @projects.page(params[:page])
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name" # Excluding ".pdf" extension.
      end
    end
  end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params.except(:employees))
    @project.creator_id = current_user.id
    @project.add_employees(project_params)
  end

  def update
    @project.add_employees(project_params)
  end

  def destroy
    @project.destroy
  end

  private

  def set_project
    @project = Project.find_by_id(params[:id])
    redirect_to(root_url, notice: "Record not found") unless @project
  end

  def set_user
    @user = User.find_by_id(current_user.id)
    redirect_to(root_url, notice: "Record not found") unless @user
  end

  def project_params
    params.require(:project).permit(:name, :description, :manager_id, :client_id, :creator_id, :cost, employees: [], files: [])
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/api/v1/admin/projects_helper.rb
# frozen_string_literal: true

module Api::V1::Admin::ProjectsHelper
end

app/helpers/api/v1/projects_helper.rb
# frozen_string_literal: true

module Api::V1::ProjectsHelper
end

app/helpers/employee/projects_helper.rb
# frozen_string_literal: true

module Employee::ProjectsHelper
end

app/helpers/manager/projects_helper.rb
# frozen_string_literal: true

module Manager::ProjectsHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
  def options_for_managers
    @managers = Manager.all
  end

  def get_clients
    @clients = Client.all
  end

  def get_client_name(id)
    @client = Client.find(id)
    @client.name
  end

  def get_company_name(id)
    @client = Client.find(id)
    @client.company
  end

  def get_user_name(id)
    @user = User.find(id)
    @user.name
  end

  def get_employees(id)
    employees = []

    Employee.joins(:projects).where(projects: { id: id }).find_each do |user|
      employees << user.name
    end
    employees
  end

  def total_payments(project)
    total = project.payments.sum(:amount)
  end

  def total_hours(project)
    total = project.time_logs.sum(:hours)
  end

  def get_time_url(current_user)
    _time_url = if current_user.admin?
                  admin_project_time_logs_path(@project)
                elsif current_user.manager?
                  manager_project_time_logs_path(@project)
                else
                  employee_project_time_logs_path(@project)
                end
  end

  def get_payment_url(current_user)
    _payment_url = if current_user.admin?
                     admin_project_payments_path(@project)
                   elsif current_user.manager?
                     manager_project_payments_path(@project)
                   else
                     ''
                   end
  end

  def get_top_projects
    Project.joins(:payments).limit(5).group(:name).sum(:amount)
  end

  def get_bottome_projects
    Project.joins(:payments).limit(5).group(:name).order('SUM(amount)').sum(:amount)
  end

  def get_top_employees
    Employee.where('time_logs.created_at > ?', Time.now - 7.days).joins('INNER JOIN time_logs ON users.id = time_logs.employee_id').limit(3).group(:name).sum(:hours)
  end

  def get_top_client
    Client.joins(:projects).limit(3).group(:name).count(:id)
  end
end

app/views/projects/_edit-form.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-9 col-md-7 col-lg-5 mx-auto'>
      <div class='card card-signin my-5'>
        <div class='card-body'>
          <h5 class='card-title text-center'>Edit Project</h5>
          <%= form_for(@project, url:_url) do |f| %>
            <div class='form-group'>
              <label>Name: </label>
              <%= f.text_field :name, autofocus: true, autocomplete: 'Name',class:'form-control' , required:true %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Description:</label>
              <%= f.text_area :description, autofocus: true, autocomplete: 'email',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Created by:</label>
              <%= f.text_field :creator_id, autofocus: true, autocomplete: 'company',class:'form-control' %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Manager:</label>
              <%= f.collection_select(:manager_id, options_for_managers, :id, :name, { prompt: 'Select manager' }, { multiple: false, class: 'form-control' }) %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Employees:</label>
              <%= f.select :employees,
               Employee.all.map { |employee| [employee.name, employee.id] },
               { include_blank: true, selected: @project.employees.pluck(:id) },
               { multiple:true,class: 'chosen-select' }
           %></div>
            <div class='form-group'>
              <label>Files:</label>
              <% project.files.each do |file| %>
                <%= hidden_field :project, :files, multiple: true, value: file.identifier %>
              <% end %>
              <%= f.file_field :files, multiple: true, class: 'form-control' %>
            </div>
            <%= f.submit('Update', class:'btn btn-primary  btn-block') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-9 col-md-7 col-lg-5 mx-auto'>
      <div class='card card-signin my-5'>
        <div class='card-body'>
          <%= form_with(model: project, url:_url,  local: true) do |f| %>
            <% if project.errors.any? %>
              <div id='error_explanation'>
                <h2><%= pluralize(project.errors.count, 'error') %> prohibited this project from being saved:</h2>
                <ul>
                  <% project.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class='form-group'>
              <label>Name:</label>
              <%= f.text_field :name, autofocus: true, autocomplete: 'name' ,class:'form-control', required:true %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Description:</label>
              <%= f.text_area :description, autofocus: true, autocomplete: 'email',class:'form-control', required:true %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Cost:</label>
              <%= f.number_field :cost,class:'form-control', min:100, required:true %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Manager:</label>
              <%= f.collection_select(:manager_id, options_for_managers, :id, :name, { prompt: 'Select manager' }, { multiple: false, class: 'form-control' }) %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Client:</label>
              <%= f.collection_select(:client_id, get_clients, :id, :name, { prompt: 'Select client' }, { multiple: false, class: 'form-control' }) %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Employees:</label>
              <%= f.select :employees,
               Employee.all.map { |employee| [employee.name, employee.id] },
               { include_blank: true },
               { multiple:true,class: 'chosen-select form-control' } %>
            </div>
            <div class='form-group'>
              <label>Files:</label>
              <% project.files.each do |file| %>
                <%= hidden_field :project, :files, multiple: true, value: file.identifier %>
              <% end %>
              <%= f.file_field :files, multiple: true, class: 'form-control' %>
            </div>
            <%= f.submit('Create', class:'btn btn-primary  btn-block') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_payment.html.erb
<table class='table' id ='payment'>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Created By:</th>
      <th>Created At:</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @payments = @project.payments.order(:created_at).page(params[:payments_page]) %>
    <% (@payments).each do |payment| %>
      <tr>
        <td><%= payment.amount %></td>
        <td><%= get_user_name(payment.creator_id) %></td>
        <td><%= payment.created_at %></td>
        <td><%= link_to(project_payment_path_path(@project,payment), class:'btn btn-info btn-xs glyphicon glyphicon-edit') do %>   <i class='fa fa-eye'></i> <% end %> </td>
      </tr>
    <%end%>
    <div id='total_payment'>
      Total:<%=total_payments(@project) %>
      <%= paginate @payments, param_name: :payments_page %>
    </div>
  </tbody>
</table>

app/views/projects/_payment_modal.html.erb
<div class=''>
  <button type='button' class='btn btn-danger' data-toggle='modal' data-target='#form3'>
    New payment
  </button>
</div>
<div class='modal fade' id='form3' tabindex='-1' role='dialog' aria-labelledby='exampleModalLabel' aria-hidden='true'>
  <div class='modal-dialog modal-dialog-centered' role='document'>
    <div class='modal-content'>
      <div class='modal-header border-bottom-0'>
        <h5 class='modal-title' id='exampleModalLabel'>Create Account</h5>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
          <span aria-hidden='true'>&times;</span>
        </button>
      </div>
      <%= form_with(model: Payment, url:_url,  remote: true) do |f| %>
        <div class='modal-body'>
          <div class='form-group'>
            <label>Cost:</label>
            <%=  f.number_field :amount,class:'form-control', min:100 %>
            <span class='Error'></span> </div>
        </div>
        <div class='modal-footer border-top-0 d-flex justify-content-center'>
            <%= f.submit('Create', class:'btn btn-primary  btn-block') %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/_search.html.erb
<div class="row">
  <%= form_tag(url, method: :get,class: 'form-horizontal col-sm-6 offset-md-3') do %>
    <%= text_field_tag :title, nil, placeholder: 'Search a project...', class: 'form-horizontal col-sm-9', required:true %>
    <%= button_tag(type: "submit", class: "btn btn-primary") do %>
      <i class="fa fa-search"></i>
    <% end %>
  <% end %>
</div>

app/views/projects/_show.html.erb
<div class=" ">
  <div class="row">
    <div class="col-xs-12 ">
      <nav>
        <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
          <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Overview</a>
          <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Employees</a>
          <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Payments</a>
          <a class="nav-item nav-link" id="nav-about-tab" data-toggle="tab" href="#nav-about" role="tab" aria-controls="nav-about" aria-selected="false">Timelogs</a>
          <a class="nav-item nav-link" id="nav-files-tab" data-toggle="tab" href="#nav-files" role="tab" aria-controls="nav-files" aria-selected="false">Files</a>
          <a class="nav-item nav-link" id="nav-comments-tab" data-toggle="tab" href="#nav-comments" role="tab" aria-controls="nav-comments" aria-selected="false">Comments</a>
        </div>
      </nav>
      <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
          <div class="well">
            <table class="table">
              <thead>
                <tr>
                  <th>Field</th>
                  <th>Details</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>Name</th>
                  <td><%= @project.name%></td>
                </tr>
                <tr>
                  <th>Description</th>
                  <td><%= @project.description %></td>
                </tr>
                <tr>
                  <th>Company</th>
                  <td><%= get_company_name(@project.client_id) %></td>
                </tr>
                <tr>
                  <th>Client</th>
                  <td><%= get_client_name(@project.client_id) %></td>
                </tr>
                <tr>
                  <th>#Employees</th>
                  <td><%= @project.employees.count %></td>
                </tr>
                <tr>
                  <th>Cost</th>
                  <td><%=%>999</td>
                </tr>
                <tr>
                  <th>Date</th>
                  <td><%= @project.created_at %></td>
                </tr>
                <tr>
                  <th>Created by:</th>
                  <td><%= get_user_name(@project.creator_id) %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
          <div class="well">
            <table class="table">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Designation</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th><%= get_user_name(@project.manager_id) %></th>
                  <td>Manager</td>
                </tr>
                <% get_employees(@project.id).each do |person| %>
                  <tr>
                    <th><%= person %></th>
                    <td>Employee</td>
                  </tr>
                <%end%>
              </tbody>
            </table>
          </div>
        </div>
        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
          <div class="well">
            <table class="table">
              <% 
              if current_user.admin? 
               _payment_url = admin_project_payments_path(@project) 
               elsif current_user.manager?
                _payment_url = manager_project_payments_path(@project)  
                else 
                _payment_url=""
                end
                %>
              <span><%= render 'payment_modal', project: @project, _url: _payment_url %> </span>
              <thead>
                <tr>
                  <th>Amount</th>
                  <th>Created By:</th>
                  <th>Created At:</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @total_amount = 0%>
                <% (@project.payments).each do |payment| %>
                  <% @total_amount = @total_amount + payment.amount%>
                  <tr>
                    <td><%= payment.amount %></td>
                    <td><%= get_user_name(payment.creator_id) %></td>
                    <td><%= payment.created_at %></td>
                    <td> <%=link_to(project_payment_path_path(@project,payment), class:"btn btn-info btn-xs glyphicon glyphicon-edit") do %>   <i class="fa fa-user"></i> <%end%> </td>
                  <%end%>
                  <tr>Total:<%=@total_amount%>  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="tab-pane fade" id="nav-about" role="tabpanel" aria-labelledby="nav-about-tab">
            <div class="well">
              <table class="table">
                <% if current_user.admin? 
               _time_url = admin_project_time_logs_path(@project) 
               elsif current_user.manager? 
                _time_url = manager_project_time_logs_path(@project)  

                else 
                _time_url = employee_project_time_logs_path(@project)  

                end
                %>
                <span><%= render 'timelog_modal', project: @project, _url: _time_url %> </span>
                <thead>
                  <tr>
                    <th>Hour(s)</th>
                    <th>Employee</th>
                    <th>Created By:</th>
                    <th>Logged At:</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @total_hours = 0%>
                  <% @project.time_logs.each do |time_log| %>
                    <% @total_hours = @total_hours + time_log.hours%>
                    <tr>
                      <td><%= time_log.hours %></td>
                      <td><%= get_user_name(time_log.employee_id) %></td>
                      <td><%= get_user_name(time_log.creator_id) %></td>
                      <td><%= time_log.created_at %></td>
                      <td> <%=link_to(project_time_log_path_path(@project,time_log), class:"btn btn-info btn-xs glyphicon glyphicon-edit") do %>   <i class="fa fa-user"></i> <%end%> </td>
                    </tr>
                  <% end %>
                  <tr>Total:<%=@total_hours%> </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="tab-pane fade" id="nav-files" role="tabpanel" aria-labelledby="nav-files-tab">
            <div class="well">
              <table class="table">
                <thead>
                  <tr>
                    <th>File</th>
                  </tr>
                </thead>
                <tbody>
                  <% @project.files.each do |file| %>
                    <tr>
                      <td><%= link_to(file) %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <div class="tab-pane fade" id="nav-comments" role="tabpanel" aria-labelledby="nav-comments-tab">
            <div class="well">Hello world
              <span><%= render 'comments/form', resource: "Project", resource_id: @project.id, object_: @project %> </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_timelog.html.erb
<table class='table' id='timelog'>
  <thead>
    <tr>
      <th>Hour(s)</th>
      <th>Employee</th>
      <th>Created By:</th>
      <th>Logged At:</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @time_logs = @project.time_logs.order(:created_at).page(params[:timelog_page]) %>
    <% @time_logs.each do |time_log| %>
      <tr>
        <td><%= time_log.hours %></td>
        <td><%= get_user_name(time_log.employee_id) %></td>
        <td><%= get_user_name(time_log.creator_id) %></td>
        <td><%= time_log.created_at %></td>
        <td><%= link_to(project_time_log_path_path(project,time_log), class:'btn btn-info btn-xs glyphicon glyphicon-edit') do %>   <i class='fa fa-eye'></i> <%end %> </td>
      </tr>
    <% end %>
    <div id='total_hours'>
      Total:<%= total_hours(@project) %>
      <%= paginate @time_logs, param_name: :timelog_page %>
    </div>
  </tbody>
</table>

app/views/projects/_timelog_modal.html.erb
<div class=''>
  <button type='button' class='btn btn-danger' data-toggle='modal' data-target='#form2'>
    New Time log
  </button>
</div>
<div class='modal fade' id='form2' tabindex='-1' role='dialog' aria-labelledby='exampleModalLabel' aria-hidden='true'>
  <div class='modal-dialog modal-dialog-centered' role='document'>
    <div class='modal-content'>
      <div class='modal-header border-bottom-0'>
        <h5 class='modal-title' id='exampleModalLabel'>Create Account</h5>
        <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
          <span aria-hidden='true'>&times;</span>
        </button>
      </div>
      <%= form_with(model: TimeLog, url:_url,  remote: true) do |f| %>
        <div class='modal-body'>
          <div class='form-group'>
            <label>Hours:</label>
            <%=  f.number_field :hours,class:'form-control', min:0 %>
            <span class='Error'></span>
          </div>
          <div class='form-group'>
            <label>Employee:</label>
            <%= f.select :employee_id,
               @project.employees.all.map { |employee| [employee.name, employee.id] },
               { include_blank: false },
               { multiple:false,class: 'chosen-select form-control' } %>
          </div>
          <div class='modal-footer border-top-0 d-flex justify-content-center'>
            <%= f.submit('Create', class:'btn btn-primary  btn-block') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class='row'>
  <%= link_to 'Back', url_for(:back), class:'btn btn-secondary pull-right' %>
</div>
<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<p id='notice'><%= notice %></p>

<h1>Projects BOO YEAH</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan='3'></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form', project: @project %>
<%= link_to 'Back', projects_path %>