config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "projects/:project_id/time_logs/:id", to: "time_logs#show", as: "project_time_log_path"
  get "projects/:project_id/payments/:id", to: "payments#show", as: "project_payment_path"

  namespace :admin do
    get "projects/index"
    get "projects/show"
  end
  namespace :api do
    namespace :v1 do
      resources :users, param: :_username
      post "/auth/login", to: "authentication#login"
      # get "/*a", to: "application#not_found"
      resource :user, controller: "profile" do
        collection do
          get "change_password"
          patch "update_password"
        end
      end
      resources :comments
      resources :projects do
        resources :payments
        resources :time_logs
      end
      resources :users
      resources :clients
    end
  end
  namespace :admin do
    match ":id" => "users#destroy", :via => :delete, :as => :user_delete
    resources :users
    resources :clients
    resources :projects do
      resources :payments
      resources :time_logs
    end
  end

  namespace :manager do
    resources :users, only: %i[index]
    resources :clients
    resources :projects do
      resources :payments
      resources :time_logs
    end
  end
  namespace :employee do
    resources :clients, only: %i[index show]
    resources :projects, only: %i[index show] do
      resources :time_logs
    end
  end
  resources :comments

  resource :user, controller: "users" do
    collection do
      get "change_password"
      patch "update_password"
    end
  end
  # get "/*a", to: "application#not_found"
  devise_for :users, controllers: { registrations: "users/registrations" }

  get "register", to: "users#new"
  post "register", to: "users#add_user"

  namespace :dashboard do
    get "dashboard/index"
  end

  get "dashboard/index"
  root to: "pages#index"

  namespace :dashboard do
    root to: "dashboard#index"
  end

  get "*path", controller: "application", action: "page_not_found"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/manager.rb
# frozen_string_literal: true

class Manager < User
  has_one :project
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  paginates_per 7
  mount_uploader :image, ImageUploader

  validates :email, uniqueness: true
  validates :name, presence: true
  validates :password, confirmation: true
  # validates :password_confirmation, presence: true
  validates :type, presence: true, inclusion: { in: %w[Admin Manager Employee],
                                                message: "%{value} is not a valid type" }

  scope :manager_filter, -> { where.not type: %w[Admin] }

  def admin?
    instance_of?(Admin)
  end

  def manager?
    instance_of?(Manager)
  end

  def client?
    instance_of?(Client)
  end

  def employee?
    instance_of?(Employee)
  end

  def type?
    type
  end

  def self.apply_filter(params)
    @users = User.all # creates an anonymous scope
    @users = @users.where("name like ?", "#{params[:name]}%") if params[:name].present?
    @users = @users.where(where email: params[:email]) if params[:email].present?
    @users
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]

  before_action :authenticate_user!

  def index
    @users = User.apply_filter(params)
    @users = @users.page(params[:page])
  end

  def new
    authorize(User)
    redirect_to(new_user_registration_path)
  end

  def update
    authorize(User)
    if @user.update(user_params)
      redirect_to dashboard_root_path, notice: 'user was successfully updated.'
    else
      render :edit
    end
  end

  def edit; end

  def destroy
    authorize(User)
    @user.destroy
    redirect_to dashboard_root_path, notice: 'User deleted.'
  end

  def user_params
    params.require(klass.to_s.underscore).permit(:name, :email, :id, :status, :image)
  end

  def set_user
    @user = User.find_by_id(params[:id])
    redirect_to(root_url, notice: 'User not found') unless @user
  end

  def klass
    @user.class
  end

  def authorize(record, query = nil)
    super([:admin, record], query)
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

class Api::V1::UsersController < Api::V1::BaseController
  before_action :set_user, only: %i[edit update destroy show]

  def index
    @users = User.apply_filter(params)
    render json: @users
  end

  def show
    render json: @user
  end

  def update
    # authorize(@user)
    if @user.update(user_params)
      render json: @user
    else
      render json: { error: "Error updating user." }
    end
  end

  def destroy
    # authorize(@client)
    @user.destroy
    render json: { message: "User deleted successfully." }
  end

  def create
    @user = User.new(user_create_params)
    if @user.save!
      render json: @user
    else
      render json: { message: "Unable to create user " }
    end
  end

  def user_create_params
    params.permit(:name, :email, :password, :type)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.permit(:name, :email, :id, :status, :image)
  end
end

app/controllers/manager/clients_controller.rb
# frozen_string_literal: true

class Manager::ClientsController < ApplicationController
  before_action :set_client, only: %i[edit update destroy show]

  def new
    authorize(Client)
  end

  def show
    authorize(@client)
  end

  def index
    authorize(Client)
    @clients = Client.apply_filter(params)
    @clients = @clients.page(params[:page])
  end

  def edit
    authorize(@client)
  end

  def update
    authorize(@client)

    if @client.update(create_params)
      redirect_to manager_client_path(@client), notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  def create
    authorize(Client)
    @client = Client.new(create_params)
    if @client.save
      redirect_to manager_client_path(@client), notice: 'Client was successfully created.'
    else
      render :new
    end
  end

  def create_params
    params.require(:client).permit(:name, :email, :company, :phone, :referred_by, :country, :compnay_phone)
  end

  def set_client
    @client = Client.find_by_id(params[:id])
    redirect_to(dashboard_root_path, notice: 'Record not found') unless @client
  end

  def authorize(record, query = nil)
    super([:manager, record], query)
  end
end

app/controllers/manager/payments_controller.rb
# frozen_string_literal: true

class Manager::PaymentsController < PaymentsController
  def new
    authorize(Payment)
    super
  end

  def update
    super
    authorize(@payment)
    if @payment.update(payment_params.except(:employees))
      redirect_to manager_project_payments_path(@project), notice: 'Payment was successfully updated.'
    else
      render :edit
    end
  end

  def create
    authorize(Payment)
    super

    if @payment.save
    else
      render :new
    end
  end

  def show
    authorize(Payment)
    super
  end

  def destroy
    authorize(Payment)
    super
  end

  def authorize(record, query = nil)
    super([:manager, record], query)
  end
end

app/controllers/manager/projects_controller.rb
# frozen_string_literal: true

class Manager::ProjectsController < ProjectsController
  def create
    authorize(Project)
    super
    if @project.save
      redirect_to manager_projects_path, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    super
    authorize(@project)

    if @project.update(project_params.except(:employees))
      redirect_to manager_projects_path, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def index
    authorize(Project)
    super
  end

  def show
    authorize(Project)
    super
    render 'projects/show', project: @project, _url: manager_project_path
  end

  def destroy
    authorize(Project)
  end

  def authorize(record, query = nil)
    super([:manager, record], query)
  end
end

app/controllers/manager/time_logs_controller.rb
# frozen_string_literal: true

class Manager::TimeLogsController < TimeLogsController
  def new
    authorize(TimeLog)
    super
  end

  def destroy
    authorize(TimeLog)
    super
    redirect_to manager_project_time_logs_path(@project), notice: 'time_log was successfully destroyed.'
  end

  def update
    super
    authorize(@time_log)
    if @time_log.update(time_log_params.except(:employees))
      redirect_to manager_project_time_logs_path(@project), notice: 'time_log was successfully updated.'
    else
      render :edit
    end
  end

  def create
    authorize(TimeLog)
    super
    if @time_log.save
    else
      render :new
    end
  end

  def authorize(record, query = nil)
    super([:manager, record], query)
  end
end

app/controllers/manager/users_controller.rb
# frozen_string_literal: true

class Manager::UsersController < ApplicationController
  def index
    @users = User.apply_filter(params)
    @users = @users.manager_filter
    @users = @users.page(params[:page])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user

  def index; end

  def edit; end

  def show; end

  def new
    authorize User
  end

  def update
    if @user.update(user_params)
      redirect_to dashboard_root_path, notice: 'user was successfully updated.'
      flash[:success] = 'Woohoo!'
    else
      render 'users/edit'
    end
  end

  def add_user
    authorize User
    @user = User.new(user_create_params)
    redirect_to root_path if @user.save!
  end

  def update_password
    @user = current_user
    if @user.update(password_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
      redirect_to root_path, notice: 'Password was successfully updated.'
    else
      render 'edit'
    end
  end

  def set_user
    @user = current_user
  end

  def password_params
    # NOTE: Using `strong_parameters` gem
    params.require(klass.to_s.underscore).permit(:password, :password_confirmation)
  end

  def user_params
    params.require(klass.to_s.underscore).permit(:name, :email, :id, :image)
  end

  def user_create_params
    params.require(:user).permit(:name, :email, :password, :type)
  end

  def klass
    @user.class
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
  def options_for_status2
    [%w[Enabled true],
     %w[Disabled false]]
  end

  def get_status(status)
    status ? 'Active' : 'inactive'
  end
end

app/helpers/api/v1/admin/users_helper.rb
# frozen_string_literal: true

module Api::V1::Admin::UsersHelper
end

app/helpers/api/v1/manager/clients_helper.rb
# frozen_string_literal: true

module Api::V1::Manager::ClientsHelper
end

app/helpers/api/v1/users_helper.rb
# frozen_string_literal: true

module Api::V1::UsersHelper
end

app/helpers/manager/clients_helper.rb
# frozen_string_literal: true

module Manager::ClientsHelper
  def options_for_countries
    [%w[Pakistan],
     %w[America]]
  end
end

app/helpers/manager/comments_helper.rb
# frozen_string_literal: true

module Manager::CommentsHelper
end

app/helpers/manager/payments_helper.rb
# frozen_string_literal: true

module Manager::PaymentsHelper
end

app/helpers/manager/projects_helper.rb
# frozen_string_literal: true

module Manager::ProjectsHelper
end

app/helpers/manager/time_logs_helper.rb
# frozen_string_literal: true

module Manager::TimeLogsHelper
end

app/helpers/manager/users_helper.rb
# frozen_string_literal: true

module Manager::UsersHelper
end

app/views/manager/users/_form.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-9 col-md-7 col-lg-5 mx-auto'>
      <div class='card card-signin my-5'>
        <div class='card-body'>
          <h5 class='card-title text-center'> </h5>
          <%= form_for(user, url:manager_user_path(@user)) do |form| %>
            <% if user.errors.any? %>
              <div id='error_explanation'>
                <h2><%= pluralize(user.errors.count, 'error') %> prohibited this user from being saved:</h2>
                <ul>
                  <%user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <%end %>
            <br style='clear:both'>
            <h3 style='margin-bottom: 25px; text-align: center;'>Edit user..</h3>
            <div class='form-group'>
              <label>Name</label>
              <%= form.text_field(:name,  class: 'form-control input_user', placeholder: 'Name', required:true) %>
            </div>
            <div class='form-group'>
              <label>Email</label>
              <%= form.text_field(:email,  class: 'form-control input_user', placeholder: 'Email', required:true) %>
            </div>
            <div class='form-group'>
              <label>Type of user:</label>
              <%= form.text_field(:type,  class: 'form-control input_user', readonly: true) %>
              <span class='Error'></span>
            </div>
            <div class='form-group'>
              <label>Current Status:</label>
              <%= form.text_field(:status,  class: 'form-control input_user', value:getStatus(:status),readonly: true) %>
              <span class='Error'></span>
            </div>
            <%= form.submit('Update', class:'btn btn-lg btn-primary btn-block ') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/manager/users/edit.html.erb
 <%= render 'form', user: @user %>

app/views/manager/users/index.html.erb
<p id='notice'><%= notice %></p>
<%= render 'dashboard/dashboard/partials/search-user', path: manager_users_path %>
<div class='row'>
  <div class='well'>
    <div class='span7'>
      <div class='widget stacked widget-table action-table'>
        <div class='widget-header'>
          <i class='icon-th-list'></i>
        </div>
        <div class='widget-content'>
          <table class='table table-striped table-bordered'>
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Type</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |person| %>
                <tr>
                  <td><%= person.name %></td>
                  <td><%= person.email %></td>
                  <td><%= person.type %></td>
                  <td><%= person.status == true ? 'Active' : 'Inactive' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @users %>
        </div>
      </div>
    </div>
  </div>
</div>