config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "projects/:project_id/time_logs/:id", to: "time_logs#show", as: "project_time_log_path"
  get "projects/:project_id/payments/:id", to: "payments#show", as: "project_payment_path"

  namespace :admin do
    get "projects/index"
    get "projects/show"
  end
  namespace :api do
    namespace :v1 do
      resources :users, param: :_username
      post "/auth/login", to: "authentication#login"
      # get "/*a", to: "application#not_found"
      resource :user, controller: "profile" do
        collection do
          get "change_password"
          patch "update_password"
        end
      end
      resources :comments
      resources :projects do
        resources :payments
        resources :time_logs
      end
      resources :users
      resources :clients
    end
  end
  namespace :admin do
    match ":id" => "users#destroy", :via => :delete, :as => :user_delete
    resources :users
    resources :clients
    resources :projects do
      resources :payments
      resources :time_logs
    end
  end

  namespace :manager do
    resources :users, only: %i[index]
    resources :clients
    resources :projects do
      resources :payments
      resources :time_logs
    end
  end
  namespace :employee do
    resources :clients, only: %i[index show]
    resources :projects, only: %i[index show] do
      resources :time_logs
    end
  end
  resources :comments

  resource :user, controller: "users" do
    collection do
      get "change_password"
      patch "update_password"
    end
  end
  # get "/*a", to: "application#not_found"
  devise_for :users, controllers: { registrations: "users/registrations" }

  get "register", to: "users#new"
  post "register", to: "users#add_user"

  namespace :dashboard do
    get "dashboard/index"
  end

  get "dashboard/index"
  root to: "pages#index"

  namespace :dashboard do
    root to: "dashboard#index"
  end

  get "*path", controller: "application", action: "page_not_found"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
# frozen_string_literal: true

class Payment < ApplicationRecord
  paginates_per 5

  belongs_to :project
  has_many :comments, as: :commentable

  validates :creator_id, presence: true
  validates :amount, presence: true, numericality: true
end

app/controllers/admin/payments_controller.rb
# frozen_string_literal: true

class Admin::PaymentsController < PaymentsController
  def new
    authorize(Payment)
    super
  end

  def update
    super
    authorize(@payment)
    if @payment.update(payment_params.except(:employees))
      redirect_to admin_project_payments_path(@project), notice: 'Payment was successfully updated. '
    else
      render :edit
    end
  end

  def destroy
    authorize(@payment)
    @payment.destroy
    redirect_to admin_project_payments_path, notice: 'Payment was successfully destroyed. '
  end

  def index
    authorize(Payment)
    super
  end

  def create
    super
    authorize(Payment)

    if @payment.save
    else
      render :new
    end
  end

  def authorize(record, query = nil)
    super([:admin, record], query)
  end
end

app/controllers/api/v1/payments_controller.rb
# frozen_string_literal: true

class Api::V1::PaymentsController < Api::V1::BaseController
  before_action :set_payment, only: %i[show edit update destroy]
  before_action :set_project, only: %i[index new show edit update destroy create]

  def index
    @payments = Payment.all
    render json: @payments
  end

  def create
    authorize(Payment)
    @payment = Payment.new(payment_params)
    @payment.project_id = @project.id
    @payment.creator_id = @current_user.id
    if @payment.save
      render_success("Successfully updated the payment", @payment)
    else
      render_errors(@payment)
    end
  end

  def destroy
    @payment.destroy
    render json: { message: "Payment deleted." }
  end

  def update
    authorize(Payment)
    if @payment.update(payment_params)
      render_success("Successfully updated the payment", @payment)
    else
      render_errors(@payment)
    end
  end

  def show
    render json: @payment
  end

  private

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:amount)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def authorize(record, query = nil)
    super([:api, :v1, record], query)
  end
end

app/controllers/manager/payments_controller.rb
# frozen_string_literal: true

class Manager::PaymentsController < PaymentsController
  def new
    authorize(Payment)
    super
  end

  def update
    super
    authorize(@payment)
    if @payment.update(payment_params.except(:employees))
      redirect_to manager_project_payments_path(@project), notice: 'Payment was successfully updated.'
    else
      render :edit
    end
  end

  def create
    authorize(Payment)
    super

    if @payment.save
    else
      render :new
    end
  end

  def show
    authorize(Payment)
    super
  end

  def destroy
    authorize(Payment)
    super
  end

  def authorize(record, query = nil)
    super([:manager, record], query)
  end
end

app/controllers/payments_controller.rb
# frozen_string_literal: true

class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]
  before_action :set_project, only: %i[index new show edit update destroy create]

  def index
    @payments = Payment.all
  end

  def show; end

  def new
    @payment = Payment.new
  end

  def edit; end

  def create
    @payment = Payment.new(payment_params)
    @payment.project_id = @project.id
    @payment.creator_id = current_user.id
  end

  def update; end

  def destroy
    authorize User, :is_admin?, policy_class: PaymentPolicy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_payment
    @payment = Payment.find_by_id(params[:id])
    redirect_to(root_url, notice: 'Record not found') unless @payment
  end

  def payment_params
    params.require(:payment).permit(:amount)
  end

  def set_project
    @project = Project.find_by_id(params[:project_id])
    redirect_to(root_url, notice: 'Record not found') unless @project
  end
end

app/helpers/admin/payments_helper.rb
# frozen_string_literal: true

module Admin::PaymentsHelper
end

app/helpers/api/v1/admin/payments_helper.rb
# frozen_string_literal: true

module Api::V1::Admin::PaymentsHelper
end

app/helpers/api/v1/payments_helper.rb
# frozen_string_literal: true

module Api::V1::PaymentsHelper
end

app/helpers/manager/payments_helper.rb
# frozen_string_literal: true

module Manager::PaymentsHelper
end

app/helpers/payments_helper.rb
# frozen_string_literal: true

module PaymentsHelper
end

app/views/payments/_admin_actions.html.erb
<span> <%= link_to(admin_project_payment_path(@project,payment), class:'btn btn-info btn-xs glyphicon glyphicon-edit') do %>   <i class='fa fa-eye'></i> <% end %> </span>
<span> <%= link_to(edit_admin_project_payment_path(@project,payment), class:'btn btn-info btn-xs glyphicon glyphicon-edit') do %>   <i class='fa fa-edit'></i> <% end %> </span>
<span> <%= link_to('Delete',admin_project_payment_path(@project,payment), method: :delete, data:{confirm: 'are you sure?'} ,class:'btn btn-warning btn-xs glyphicon glyphicon-edit') %></span>

app/views/payments/_edit-form.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-9 col-md-7 col-lg-5 mx-auto'>
      <div class='card card-signin my-5'>
        <div class='card-body'>
          <h5 class='card-title text-center'>Edit Project</h5>
          <%= form_for(@payment, url:_url) do |f| %>
            <div class='form-group'>
              <label>Cost:</label>
              <%=  f.number_field :amount,class:'form-control', min:100, required:true %>
              <span class='Error'></span>
            </div>
            <%= f.submit('Update', class:'btn btn-primary  btn-block') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/payments/_form.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-sm-9 col-md-7 col-lg-5 mx-auto'>
      <div class='card card-signin my-5'>
        <div class='card-body'>
          <%= form_with(model: Payment, url:_url,  local: true) do |f| %>
            <% if project.errors.any? %>
              <div id='error_explanation'>
                <h2><%= pluralize(project.errors.count, 'error') %> prohibited this project from being saved:</h2>
                <ul>
                  <% project.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class='form-group'>
              <label>Cost:</label>
              <%=  f.number_field :amount,class:'form-control', min:100 , required:true %>
              <span class='Error'></span>
            </div>
            <%= f.submit('Create', class:'btn btn-primary  btn-block')%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/payments/_manager_actions.html.erb
<span> <%= link_to(manager_project_payment_path(@project,payment), class:'btn btn-info btn-xs glyphicon glyphicon-edit') do %>   <i class='fa fa-eye'></i> <% end %> </span>
<span> <%= link_to(edit_manager_project_payment_path(@project,payment), class:'btn btn-info btn-xs glyphicon glyphicon-edit') do %>   <i class='fa fa-edit'></i> <% end %> </span>

app/views/payments/index.html.erb
<div class='row'>
  <%= link_to 'Back', url_for(:back), class:'btn btn-secondary pull-right' %>
</div>
<div class='row'>
  <%= link_to(new_manager_project_payment_path(@project), class:'btn btn-primary btn-xs pull-left' )do %><i class='fa fa-eye'> Create payment</i> <% end %>
</div>
<div class='row'>
  <div class='span7'>
    <div class='widget stacked widget-table action-table'>
      <div class='widget-header'>
        <i class='icon-th-list'></i>
        <h3>Projects</h3>
      </div>
      <div class='widget-content'>
        <table class='table table-striped table-bordered'>
          <thead>
            <tr>
              <th>Amount</th>
              <th>Created by</th>
              <th>Created on</th>
              <th>Actions </th>
            </tr>
          </thead>
          <tbody>
            <% @payments.each do |payment| %>
              <tr>
                <td><%= payment.amount %></td>
                <td><%= get_user_name(payment.creator_id) %></td>
                <td><%= payment.created_at %></td>
                <td>
                  <% if current_user.manager? %>
                    <%= render 'manager_actions', payment: payment, project: @project %>
                  <% else %>
                    <%= render 'admin_actions', payment: payment, project: @project %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- /widget-content -->
    </div>
    <!-- /widget -->
  </div>
</div>

app/views/payments/new.html.erb
<div class='row'>
  <%= link_to 'Back', url_for(:back), class:'btn btn-secondary pull-right' %>
</div>
<%= render 'form', project: @project %>

app/views/payments/show.html.erb
<div class=' '>
  <div class='row'>
    <div class='col-xs-12 '>
      <nav>
        <div class='nav nav-tabs nav-fill' id='nav-tab' role='tablist'>
          <a class='nav-item nav-link active' id='nav-home-tab' data-toggle='tab' href='#nav-home' role='tab' aria-controls='nav-home' aria-selected='true'>Overview</a>
          <a class='nav-item nav-link' id='nav-profile-tab' data-toggle='tab' href='#nav-profile' role='tab' aria-controls='nav-profile' aria-selected='false'>Comments</a>
        </div>
      </nav>
      <div class='tab-content py-3 px-3 px-sm-0' id='nav-tabContent'>
        <div class='tab-pane fade show active' id='nav-home' role='tabpanel' aria-labelledby='nav-home-tab'>
          <div class='well'>
            <table class='table'>
              <thead>
                <tr>
                  <th>Field</th>
                  <th>Details</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>Project Name</th>
                  <td><%= @project.name %></td>
                </tr>
                <tr>
                  <th>Description</th>
                  <td><%= @project.description %></td>
                </tr>
                <tr>
                  <th>Amount</th>
                  <td><%= @payment.amount %></td>
                </tr>
                <tr>
                  <th>Created by</th>
                  <td><%= get_user_name(@payment.creator_id) %></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class='tab-pane fade' id='nav-profile' role='tabpanel' aria-labelledby='nav-profile-tab'>
          <div class='well'>
            <span><%= render 'comments/form', resource: 'Payment', resource_id: @payment.id, object_: @payment %> </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>